
title: JustinHolcomb.me
description: Ramblings about technology.
baseurl             : ""
repository          : EpiJunkie/epijunkie.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Justin Holcomb
  image             : /assets/img/avatar.jpg
# behance           : your_username
# dribbble          : your_username
# email             : username@domain.com
# facebook          : your_username
  github            : EpiJunkie
# gitlab            : your_username
  instagram         : casualsupercar
# kaggle            : your_username
  linkedin          : justindholcomb
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title

### Disqus ###
disqus:
  shortname: justinholcomb-me

### Analytics ###
analytics:
  enabled: true
  google:
    tracking_id: UA-78748357-1

### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: true
  username: epijunkie
  color: "#007bff"
  message: "Thank you for visiting!"
  description: "Support this site remain ad-free by buying me tacos!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - _config.yml
  - "*.log"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
